preupg/ui/report/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required as lr

from .views import RunsView, ReportView, NewRunView, NewHostView, DeleteOlderView, \
    NewLocalRunView, ReportFilesView, RunView, DeleteRunView, ResultViewAjax

urlpatterns = patterns(
    '',
    url(r'^$', lr(RunsView.as_view()), name='index'),
    url(r'^$', lr(RunsView.as_view()), name='results-list'),
    url(r'^delete-older/$', lr(DeleteOlderView.as_view()), name='delete-older'),
    url(r'^(?P<result_id>\d+)/detail/$', lr(RunView.as_view()), name='result-detail'),
    #url(r'^run/(?P<run_id>\d+)/$', lr(RunView.as_view()), name='run'),
    # TODO: creating runs from UI is not done and ready for production
    #url(r'^new/$', lr(NewRunView.as_view()), name='new-run'),
    #url(r'^new-local-run/$', lr(NewLocalRunView.as_view()), name='new-local-run'),
    #url(r'^new-host/$', lr(NewHostView.as_view()), name='new-host'),
    url(r'^(?P<result_id>\d+)/report/$', lr(ReportView.as_view()),  name='show-report'),
    url(r'^(?P<result_id>\d+)/file/$', lr(ReportFilesView.as_view()),        name='show-file'),
    url(r'^(?P<result_id>\d+)/ajax/$', lr(ResultViewAjax.as_view()), name='show-result-ajax'),
    url(r'^(?P<result_id>\d+)/delete/$', lr(DeleteRunView.as_view()), name='result-delete'),
)

preupg/ui/urls.py
from django import VERSION
from django.conf.urls import patterns, include, url
from django.contrib import admin
from preupg.ui.auth.views import FirstRunView, FirstRunDisableAuthView, login, logout
from preupg.ui.auth.decorators import first_run_required as frr

if VERSION < (1, 7):
    admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('preupg.ui.report.urls')),

    #url(r'^settings/', include('preupg.ui.config.urls')),

    url(r"^xmlrpc/", include("preupg.ui.xmlrpc_backend.urls"), name="xmlrpc"),

    # shortcut for XML-RPC submission
    url(r"^submit/$", "preupg.ui.xmlrpc_backend.views.submission_handler", name="xmlrpc-submit"),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^compare/', include('preupg.ui.compare.urls')),

    # private auth URLs
    url(r'^auth/', include('preupg.ui.auth.urls')),

    # public auth URLs -- first display and login itself
    url(r'^login/$', login, {'template_name': 'auth/login.html'}, name='auth-login'),
    url(r'^logout/$', logout, {'template_name': 'auth/logout.html'}, name='auth-logout'),
    url(r'^first/$', frr(FirstRunView.as_view()), name='first-run'),
    url(r'^first/disable/$', frr(FirstRunDisableAuthView.as_view()), name='first-run-disable-auth'),
)

preupg/ui/report/models.py
# -*- coding: utf-8 -*-
""" Database schema """
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.db.models.aggregates import Count
from django.http.response import Http404
import os
import datetime

from django.db import models
from django.conf import settings
from preupg.ui.config.models import AppSettings
from preupg.ui.utils.enum import Enum
from shutil import rmtree


class OS(models.Model):
    RHEL5 = 5
    RHEL6 = 6
    RHEL7 = 7

    MAJOR_VERSIONS = Enum([
        (RHEL5, 'RHEL-5', 'Red Hat Enterprise Linux 5'),
        (RHEL6, 'RHEL-6', 'Red Hat Enterprise Linux 6'),
        (RHEL7, 'RHEL-7', 'Red Hat Enterprise Linux 7'),
    ])
    major = models.SmallIntegerField(choices=MAJOR_VERSIONS.get_mapping())
    minor = models.SmallIntegerField()

    class Meta:
        ordering = ('major', 'minor')

    def __unicode__(self):
        return u"%s.%d" % (self.MAJOR_VERSIONS.get_help(self.major),
                           self.minor)


class Host(models.Model):
    """
    host where analysis was executed
    creds are required for distributive execution
    """
    hostname = models.CharField(max_length=255)
    ssh_name = models.CharField(max_length=255, blank=True, null=True)
    # TODO: security \/
    ssh_password = models.CharField(max_length=255, blank=True, null=True)
    sudo_password = models.CharField(max_length=255, blank=True, null=True)
    su_login = models.CharField(max_length=255, blank=True, null=True,
                                help_text="Alternative user")
    local = models.BooleanField(default=False, help_text="Local analysis")

    os = models.ForeignKey(OS, blank=True, null=True)

    class Meta:
        ordering = ('hostname',)

    def __unicode__(self):
        return u"%s (%s)" % (self.hostname, self.os)

    @classmethod
    def localhost(cls):
        return cls.objects.get(hostname="localhost")


class TestGroupMixin(object):
    def create_or_update(self, k):
        """
        return Test object for specified id_ref rule
        """
        try:
            tg = self.get(xccdf_id=k['xccdf_id'])
        except ObjectDoesNotExist:
            tg = TestGroup(**k)
            tg.save()
        else:
            self.filter(pk=tg.pk).update(**k)
        return tg

    def root(self):
        return self.filter(parent__isnull=True)


class TestGroupQuerySet(models.query.QuerySet, TestGroupMixin):
    pass


class TestGroupManager(models.Manager, TestGroupMixin):
    def get_query_set(self):
        return TestGroupQuerySet(self.model, using=self._db)


class TestGroup(models.Model):
    """
    Tests are composed into groups, user may pick which groups to choose
    """
    title = models.CharField(max_length=255, db_index=True)
    xccdf_id = models.CharField(max_length=128)
    parent = models.ForeignKey('self', blank=True, null=True)

    objects = TestGroupManager()

    class Meta:
        ordering = ('title', )

    def __unicode__(self):
        if self.parent:
            return u"%s [%s]" % (self.title, self.parent)
        else:
            return u"%s" % (self.title)

    def has_children(self):
        return TestGroup.objects.filter(parent=self).exists()

    def children(self):
        return TestGroup.objects.filter(parent=self)

    def is_root(self):
        """ is this group root group? == does it have parent? """
        return self.parent is None


class TestGroupResultMixin(object):
    def for_result(self, result):
        return self.filter(result=result)

    def search_in_title(self, query_string):
        return self.filter(group__title__icontains=query_string)

    def root(self):
        return self.filter(parent__isnull=True)


class TestGroupResultQuerySet(models.query.QuerySet, TestGroupResultMixin):
    pass


class TestGroupResultManager(models.Manager, TestGroupResultMixin):
    def get_query_set(self):
        return TestGroupResultQuerySet(self.model, using=self._db)


class TestGroupResult(models.Model):
    """
    Result of test group -- combine run and testgroup together
    """
    group = models.ForeignKey(TestGroup)
    result = models.ForeignKey('Result')
    parent = models.ForeignKey('self', related_name="direct_children_set", blank=True, null=True)
    # this should never be None, but if this group is root also, it has to be saved first
    root = models.ForeignKey('self', related_name="all_children_set", blank=True, null=True)

    test_count = models.SmallIntegerField(blank=True, null=True, default=0)
    failed_test_count = models.SmallIntegerField(blank=True, null=True, default=0)
    ni_test_count = models.SmallIntegerField(blank=True, null=True, default=0)
    na_test_count = models.SmallIntegerField(blank=True, null=True, default=0)

    objects = TestGroupResultManager()

    class Meta:
        ordering = ('group', )

    def __unicode__(self):
        return u"%s %s" % (self.group, self.result)

    def has_children(self):
        return TestGroupResult.objects.filter(parent=self).exists()

    def children(self):
        return TestGroupResult.objects.filter(parent=self)

    def testresults(self):
        return self.testresult_set.all()

    def get_root(self):
        """ return root group -- top-most parent """
        if self.root is not None:
            return self.root
        group = self
        parent = self.parent
        while parent is not None:
            group = parent
            parent = group.parent
        self.root = group
        self.save()
        return group

    #def title_matches_filter(self, search_string):
    #    """ does this group matches searching? """
    #    return search_string.lower() in self.group.title


class RunMixin(object):

    def create_for_host(self, host):
        run = Run()
        run.save()
        HostRun.objects.create(host=host, run=run)
        return run

    def bulk_create_for_run(self, hosts):
        """
        create hostruns for list of hosts specified as Query in variable hosts
        """
        run = Run()
        run.save()
        hostrun_list = []
        for host in hosts:
            hostrun_list.append(HostRun(host=host, run=run))

        HostRun.objects.bulk_create(hostrun_list)
        return run


class RunQuerySet(models.query.QuerySet, RunMixin):
    pass


class RunManager(models.Manager, RunMixin):
    def get_query_set(self):
        return RunQuerySet(self.model, using=self._db)


class Run(models.Model):
    """
    one run may consist of several results (from multiple hosts)
    """
    dt_submitted = models.DateTimeField(auto_now_add=True)
    dt_finished = models.DateTimeField(blank=True, null=True)
    objects = RunManager()

    class Meta:
        ordering = ('-dt_submitted', )

    def __unicode__(self):
        if not self.dt_finished:
            return u"#%d %s (running)" % (self.id, self.dt_submitted)
        else:
            return u"#%d %s--%s" % (self.id, self.dt_submitted,
                                    self.dt_finished)

    def results(self):
        """ Return all Results from this run"""
        return Result.objects.filter(hostrun__run=self)

    def testresults(self):
        """ Return all TestResults from this run"""
        return TestResult.objects.filter(group__result__hostrun__run=self)

    def get_run_dir(self):
        results_dir = os.path.abspath(settings.RESULTS_DIR)
        path = os.path.join(results_dir, str(self.id))
        if not os.path.isdir(path):
            os.makedirs(path, mode=0o0755)
        return path

    def has_local(self):
        """ should there be some scan performed locally? """
        return self.hostrun_set.filter(host__local=True).exists()

    def local(self):
        """ return local hostrun assigned to this run """
        return HostRun.objects.get(run=self, host__local=True)

    def remotes(self):
        """ Return remote HostRuns """
        return HostRun.objects.filter(run=self, host__local=False)

    def all_done(self):
        """ if there are no running tasks, everything is done """
        return not HostRun.objects.for_run(self).running().exists()

    def finish(self):
        self.dt_finished = datetime.datetime.now()
        self.save(update_fields=["dt_finished"])

    def first_hostrun(self):
        return self.hostrun_set.all()[0]


class HostRunMixin(object):
    def for_run(self, run):
        return self.filter(run=run)

    def for_result(self, result_id):
        result = self.filter(result=result_id)
        if not result:
            raise Http404('There is no such run.')
        else:
            return result

    def running(self):
        return self.filter(state=HostRun.RUNNING)

    def finished(self):
        return self.filter(state=HostRun.FINISHED)

    def hosts(self):
        """ return list of hostname strings found in hostruns """
        return self.values_list("result__hostname", flat=True)

    def risks(self):
        """ return list of risk strings found in hostruns """
        return self.values_list("risk", flat=True).distinct()

    def by_risk(self, risk):
        return self.filter(risk=risk)

    def by_hosts_processed(self, hosts):
        return self.filter(result__hostname__in=hosts)


class HostRunQuerySet(models.query.QuerySet, HostRunMixin):
    pass


class HostRunManager(models.Manager, HostRunMixin):
    def get_query_set(self):
        return HostRunQuerySet(self.model, using=self._db)


class HostRun(models.Model):
    """
    M2M relationship between run and hosts -- Run on each Host
    """
    RUNNING = 'r'
    FINISHED = 'f'

    RUN_STATES = Enum([
        (RUNNING, 'running', 'Scan is active.'),
        (FINISHED, 'finished', 'Scan has finished.'),
    ])
    dt_finished = models.DateTimeField(blank=True, null=True)
    host = models.ForeignKey(Host)
    run = models.ForeignKey(Run)
    state = models.CharField(max_length=1, choices=RUN_STATES.get_mapping(), default=RUNNING, db_index=True)

preupg/ui/report/forms.py
# -*- coding: utf-8 -*-
from django.db.models import Q

from django import forms

from .models import Host, HostRun, TestResult


class NewHostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewHostForm, self).__init__(*args, **kwargs)
        self.fields['ssh_name'].label = "SSH Login"
        self.fields['ssh_password'].label = "SSH Password"
        self.fields['sudo_password'].label = "sudo Password"
        self.fields['su_login'].label = "su Login"
        self.fields['local'].label = "Local scan"

    class Meta:
        model = Host


class NewRunForm(forms.Form):

    hosts = forms.ModelMultipleChoiceField(queryset=Host.objects.all())
    #tests = forms.ModelMultipleChoiceField(queryset=TestGroup.objects.all())

    def __init__(self, *args, **kwargs):
        super(NewRunForm, self).__init__(*args, **kwargs)
        self.fields['hosts'].label = "Hosts"


class FilterForm(forms.Form):
    """
    form displayed in the toolbar, you can filter runs by host, risk level or just plain search
    """
    search = forms.CharField(required=False, widget=forms.TextInput(
        attrs={
            'id': 'global-search',
            'placeholder': "Search...",
            'class': 'form-control',
        })
    )
    hosts = forms.MultipleChoiceField(required=False, widget=forms.SelectMultiple(
        attrs={
            'class': 'selectpicker global-filter host-filter',
            'data-live-search': 'true',
        })
    )
    risk = forms.ChoiceField(required=False, widget=forms.Select(
        attrs={
            'class': 'selectpicker global-filter risk-filter',
        })
    )


    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        risk_choices = []
        for risk in HostRun.objects.risks():
            if risk and risk not in risk_choices:
                risk_choices.append(risk)
        risk_choices = zip(risk_choices, [risk.capitalize() for risk in risk_choices])
        # first option searches in every release
        risk_choices.insert(0, ('', 'All Risk Levels'))
        self.fields['risk'].choices = risk_choices

        host_choices = [(hr['host__hostname'], hr['host__hostname'])
            for hr in HostRun.objects.values('host__hostname').order_by('host__hostname').distinct()
        ]
        # first option searches in every release
        host_choices.insert(0, ('', 'All Hosts'))
        self.fields['hosts'].choices = host_choices

    def is_valid(self):
        valid = super(FilterForm, self).is_valid()
        if not valid:
            return valid
        if not self.cleaned_data['hosts'] and not self.cleaned_data['risk'] and not self.cleaned_data['search']:
            return False
        return True

class StateFilterForm(forms.Form):
    """ filter test results by their state """

    def __init__(self, *args, **kwargs):
        result = kwargs.pop('result')
        super(StateFilterForm, self).__init__(*args, **kwargs)

        states = result.states()

        #states.insert(0, ('', 'All'))

        self.blacklisted_states = ['notchecked']

        sorted_mapping = sorted(TestResult.TEST_STATES.get_mapping(), key=lambda x: x[0])

        for state_key, state_css in sorted_mapping:
            try:
                print_state = states[state_css]
            except KeyError:
                if not TestResult.TEST_STATES[state_key] in self.blacklisted_states:
                    print_state = "%s (0)" % TestResult.TEST_STATES.display(state_key)
                else:
                    continue
            field_name = state_css + str(result.id)
            self.fields[field_name] = forms.BooleanField(label=print_state, required=False)
        #self.fields[field_name].widget.attrs['class'] = "state-filter"
        #self.fields[field_name].widget.attrs['multiple'] = "multiple"
        #try:
        #    initial = args[0]
        #except IndexError:
        #    pass
        #else:
        #    self.fields[field_name].initial = initial

    def all_checked(self):
        return len(self.initial) >= len(TestResult.TEST_STATES.get_mapping()) - len(self.blacklisted_states)


class ListActionForm(forms.Form):
    ACTIONS = {
        'delete_selected': 'Delete selected',
    }
    runs    = forms.MultipleChoiceField()
    action  = forms.ChoiceField(choices=ACTIONS.items())
    confirm = forms.BooleanField(required=False)


class DeleteOlderForm(forms.Form):
    host = forms.ChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        super(DeleteOlderForm, self).__init__(*args, **kwargs)
        host_choices = [(hr['host__hostname'], hr['host__hostname'])
            for hr in HostRun.objects.values('host__hostname').order_by('host__hostname').distinct()
        ]
        self.fields['host'].choices = host_choices

preupg/ui/templates/report/hostrun_confirm_delete.html
{% extends "base.html" %}

{% block nav_results %}active{% endblock %}
{% block content %}
<div class="row col-sm-7 col-md-6 col-lg-5">
      <h3>{% block title %}Delete results{% endblock %}</h3>
      {% if form.errors %}
      <div class="alert alert-danger">
        <span class="pficon-layered">
          <span class="pficon pficon-error-octagon"></span>
          <span class="pficon pficon-error-exclamation"></span>
        </span>
        {% for key, value in form.errors.items %}
          {% for error in value %}
            <div>{{ error }}</div>
          {% endfor %}
        {% endfor %}
      </div>
      {% endif %}
      <form class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <div class="form-group">
          <div class="col-sm-12 col-md-12">
            Are you sure you want to delete result "<b>{{ hostrun.result.dt_finished|date:"Y-m-d H:i:s" }},
            {% if hostrun.result %}{{ hostrun.result.hostname|default_if_none:"" }}{% else %}{{ hostrun.host.hostname }}
            {% endif %}</b>"?
          </div>
          <div class="col-sm-12 col-md-12 submit">
            <a class="btn btn-default btn-lg" href="{% url 'results-list' %}">Back</a>
            <button type="submit" class="btn btn-primary btn-lg" tabindex="2">Confirm</button>
          </div>
        </div>
      </form>
</div><!--/.row-->
{% endblock %}

preupg/ui/templates/report/hostrun_delete_older.html
{% extends "base.html" %}

{% block nav_results %}active{% endblock %}

{% block content %}
<div class="row col-sm-7 col-md-6 col-lg-5">
      <h3>{% block title %}Delete older results{% endblock %}</h3>
      <p>It will keep only the last resutls for each host.</p>
      {% if form.errors %}
      <div class="alert alert-danger">
        <span class="pficon-layered">
          <span class="pficon pficon-error-octagon"></span>
          <span class="pficon pficon-error-exclamation"></span>
        </span>
        {% for key, value in form.errors.items %}
          {% for error in value %}
            <div>{{ error }}</div>
          {% endfor %}
        {% endfor %}
      </div>
      {% endif %}
      <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="form-group">
          <div class="col-sm-12">
              <p>Are you sure you want to delete these results?</p>
              <ul class="hostruns">
              {% for hostrun in hostruns %}
                  <li>
                      <input type="hidden" name="runs" value="{{ hostrun.id }}"/>
                      <span class="row-title">{{ hostrun.result.dt_finished|date:"Y-m-d H:i:s" }}</span>,
                      {% if hostrun.result %}{{ hostrun.result.hostname|default_if_none:"" }}{% else %}{{ hostrun.host.hostname }}{% endif %}
                  </li>
              {% endfor %}
              </ul>
          </div>
          <div class="col-sm-12 submit">
              <a class="btn btn-default btn-lg" href="{% url 'results-list' %}?{{ request.META.QUERY_STRING }}">Back</a>
              <button type="submit" class="btn btn-primary btn-lg" name="confirm" value="confirm" tabindex="2">Confirm</button>
          </div>
        </div>
      </form>
</div><!--/.row-->
{% endblock %}

preupg/ui/templates/report/hostrun_delete_selected.html
{% extends "base.html" %}

{% block nav_results %}active{% endblock %}
{% block content %}
<div class="row col-sm-7 col-md-6 col-lg-5">
      <h3>{% block title %}Delete selected results{% endblock %}</h3>
      {% if form.errors %}
      <div class="alert alert-danger">
        <span class="pficon-layered">
          <span class="pficon pficon-error-octagon"></span>
          <span class="pficon pficon-error-exclamation"></span>
        </span>
        {% for key, value in form.errors.items %}
          {% for error in value %}
            <div>{{ error }}</div>
          {% endfor %}
        {% endfor %}
      </div>
      {% endif %}
      <form class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="delete_selected"/>
        <input type="hidden" name="confirm" value="1"/>
        {% for hostrun in hostruns %}
        <input type="hidden" name="runs" value="{{ hostrun.id }}"/>
        <span class="row-title">{{ hostrun.result.dt_finished|date:"Y-m-d H:i:s" }}</span>,
        {% if hostrun.result %}{{ hostrun.result.hostname|default_if_none:"" }}{% else %}{{ hostrun.host.hostname }}{% endif %}<br/>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-12 col-md-12">
            Are you sure you want to delete the results?
          </div>
          <div class="col-sm-12 col-md-12 submit">
            <a class="btn btn-default btn-lg" href="{% url 'results-list' %}?{{ request.META.QUERY_STRING }}">Back</a>
            <button type="submit" class="btn btn-primary btn-lg" tabindex="2">Confirm</button>
          </div>
        </div>
      </form>
</div><!--/.row-->
{% endblock %}

preupg/ui/templates/report/new_run.html
{% extends "base.html" %}
{% block nav_new-run %}active{% endblock %}
{% block content %}
{% comment %} {# FIXME: improve this #}
<div id="new-host-container">
    <form class="new-host-form" method="post" action="{% url "new-host" %}">
        {% csrf_token %}
    {% for field in new_host_form %}
        <div class="fieldWrapper">
            {{ field.errors }}
        {{ field.label_tag }}: {{ field }}
        </div>
        {% endfor %}
        <input class="btn" type="submit" value="Create" name="submit" />
    </form>
</div>
<div id="new-run-container">
    <form class="new-run-form" method="post" action="{% url "new-run" %}">
        {% csrf_token %}
    {% for field in new_run_form %}
        <div class="fieldWrapper">
            {{ field.errors }}
        {{ field.label_tag }}: {{ field }}
        </div>
        {% endfor %}
        <input class="btn" type="submit" value="Run!" name="submit" />
    </form>
</div>
{% endcomment %}
<div class="new-run-container">
    <h1 class="center">{% block title %}Run locally{% endblock %}</h1>
    <div class="helper-text">
        This will initiate a new run locally. It may take a few minutes to complete the scan.
    </div>
    <div class="center">
        <a href="{% url "new-local-run" %}" class="btn btn-default">Run locally</a>
    </div>
</div>
{% endblock %}

preupg/ui/templates/report/test.html
{% for tr in group.filtered_tests %}
    <li id="testresult-{{ tr.id }}-group-{{ group.id }}" class="test-row-container state-{{ tr.get_state_display }}" style="display: none;">
        <div class="test-row link">
            {# STATUS #}
            <div class="col left-col bg-{{ tr.get_state_display }} test-status">{{ tr.display_state }}</div>
            {# TITLE #}
            <div class="col right-col">
                <span class="icon fa closed left-{{ left_margin }}"></span>
                <span class="test-title">{{ tr.test.title }}</span>
            </div>
        </div>
        <div id="testresult-{{ tr.id }}-results" class="test-info-row" style="display: none;">
            <div class="col left-col"></div>
            <div class="test-result-container right-col">
                <div class="test-result-inner-container double-left-{{ left_margin }}">
                    <h2>Description</h2>
                    <div class="test-description">
                        {{ tr.test.description|safe }}
                    </div>
                    {% if tr.risks %}
                    <h2>Risks</h2>
                        <ul class="risk-list">
                        {% for risk in tr.risks %}
                            <li><span class="status-box border-{{risk.level.lower}}">{{ risk.level|upper }}</span>{{ risk.message }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}

                    {% if tr.test.fix %}
                    <h2>Solution Script</h2>
                    {{ tr.test.fix|linebreaksbr }}
                    {% endif %}

                    {% if tr.test.fixtext and tr.should_display_solution %}
                        <h2>Solution</h2>
                        <div class="solution-text">
                        {{ tr.test.fixtext|safe }}
                        </div>
                    {% endif %}
                    {% if tr.logs %}
                    <table cellspacing="0"> {# LOGS #}
                        <thead>
                            <tr>
                                <th>
                                    Date
                                </th>
                                <th>
                                    Level
                                </th>
                                <th>
                                    Message
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for log in tr.logs %}
                            <tr class="log">
                                <td>{{ log.date }}</td>
                                <td>{{ log.level }}</td>
                                <td>{{ log.message }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </li>
{% endfor %}